import logging
import os

from google.adk.agents import Agent

logger = logging.getLogger("ai_creative_studio.designer")

# TODO: Define SYSTEM_INSTRUCTION
# The Designer creates Imagen-ready image generation prompts. It should:
#   - Read the Copywriter's captions AND the Brand Strategist's insights from the conversation history
#   - Create 2-3 visual concepts per caption
#   - Each concept must include: prompt, style, colors, mood
#   - Target Instagram dimensions (1080x1080 square or 1080x1350 portrait)
#
# Output format per caption:
#   **For Caption [N]: [Caption Theme]**
#   **Concept A: [Visual Theme]**
#   - Prompt: [Detailed Imagen prompt]
#   - Style: [e.g., minimalist, vibrant, cinematic]
#   - Colors: [Palette]
#   - Mood: [e.g., energetic, calm, inspiring]
#
# Note: The agent creates prompts for image generation, not actual images.
SYSTEM_INSTRUCTION = """
# TODO: Write the Designer system instruction here
"""

# TODO: Create the root_agent
# No tools needed — visual concepts are generated by the LLM
root_agent = Agent(
    name="designer",
    model="gemini-2.5-flash",
    # TODO: add instruction=SYSTEM_INSTRUCTION
    # TODO: add description=
)

logger.info("Designer agent created")


if __name__ == "__main__":
    import uvicorn
    from google.adk.a2a.utils.agent_to_a2a import to_a2a

    PORT = int(os.getenv("PORT", "8080"))
    HOST = os.getenv("HOST", "0.0.0.0")
    PUBLIC_HOST = os.getenv("PUBLIC_HOST", "localhost")
    PUBLIC_PORT = int(os.getenv("PUBLIC_PORT", str(PORT)))
    PROTOCOL = os.getenv("PROTOCOL", "http")

    a2a_app = to_a2a(root_agent, host=PUBLIC_HOST, port=PUBLIC_PORT, protocol=PROTOCOL)

    logger.info(f"Starting Designer on {PROTOCOL}://{HOST}:{PORT}")
    logger.info(f"Agent card: {PROTOCOL}://{HOST}:{PORT}/.well-known/agent.json")

    uvicorn.run(a2a_app, host=HOST, port=PORT)
